version: '3.8'

services:

  signflow-db:

    image: postgres:16

    container_name: signflow-db

    restart: always

    environment:
      POSTGRES_DB: signflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:

    build: .

    container_name: signflow-app

    restart: always

    depends_on:
      - signflow-db

    environment:

      SPRING_PROFILES_ACTIVE: prod

      SERVER_PORT: 8081

      JWT_SECRET: signflow-secret

      SIGNFLOW_ENCRYPTION_KEY: "signflow-encryption-key-prod-2026"

      CLICKSIGN_URL: https://sandbox.clicksign.com

      CLICKSIGN_API_TOKEN: test-token

      CLICKSIGN_WEBHOOK_SECRET: webhook-secret

      SPRING_DATASOURCE_URL: jdbc:postgresql://signflow-db:5432/signflow

    ports:
      - "8081:8081"

volumes:
  postgres_data: