signflow:
  providers:
    clicksign:
      enabled: true
      base-url: ${CLICKSIGN_URL:https://sandbox.clicksign.com/api/v3}
      token: ${CLICKSIGN_API_TOKEN:e6acc96a-bfba-40fc-8248-62727f4f632e}
      webhook-secret: ${CLICKSIGN_WEBHOOK_SECRET:}
    docusign:
      enabled: false
      base-url: ${DOCUSIGN_URL:}
    zapsign:
      enabled: false
      base-url: ${ZAPSIGN_URL:}

server:
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true

swagger:
  server-url: ${SWAGGER_SERVER_URL:}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/signflow
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
resilience4j:
  circuitbreaker:
    instances:
      clicksign-circuit-breaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:
      userRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 0
        registerHealthIndicator: true
      ipRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 0
        registerHealthIndicator: true
    rate-limiter-aspect-order: 0

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  pattern:
    level: "%5p [requestId=%X{requestId}] [userId=%X{userId}]"
