signflow:
  encryption:
    key: ${SIGNFLOW_ENCRYPTION_KEY:}
  providers:
    clicksign:
      enabled: true
      base-url: ${CLICKSIGN_URL:https://sandbox.clicksign.com/api/v3}
      token: ${CLICKSIGN_API_TOKEN:}
      webhook-secret: ${CLICKSIGN_WEBHOOK_SECRET:}
    docusign:
      enabled: false
      base-url: ${DOCUSIGN_URL:}

server:
  forward-headers-strategy: framework
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true

swagger:
  server-url: ${SWAGGER_SERVER_URL:}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/signflow}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: false
    clean-disabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: signflow-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.signflow.*"

resilience4j:
  circuitbreaker:
    instances:
      clicksign-circuit-breaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:
      userRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 0
        registerHealthIndicator: true
      ipRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 0
        registerHealthIndicator: true
    rate-limiter-aspect-order: 0

security:
  jwt:
    secret: ${JWT_SECRET:}
    expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  pattern:
    level: "%5p [requestId=%X{requestId}] [userId=%X{userId}]"
  level:
    root: INFO
    com.signflow: INFO
    org.hibernate.SQL: WARN