package com.signflow.domain.exception;

import lombok.Getter;

@Getter
public enum DomainErrorCode {
    NOT_FOUND,
    INVALID_ENVELOPE_STATUS,
    REMINDER_RATE_LIMIT,
    INVALID_AUTH_METHOD,
    BUSINESS_RULE_VIOLATION,
    USER_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    USER_NOT_FOUND,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_NOT_FOUND,
    ACCOUNT_LOCKED,
    INVALID_CREDENTIALS,
    PASSWORD_ALREADY_USED,
    PASSWORD_EXPIRED
}
