-- ================================================================
-- SignFlow — V1_
--
-- Schema consolidado: 9 migrations (V1→V9) em um único arquivo.
-- Gerado para ambiente de desenvolvimento — banco zerado.
--
-- Para aplicar:
--   1. Apagar o banco e recriar: DROP DATABASE signflow; CREATE DATABASE signflow;
--   2. Remover os arquivos V2 a V9 do diretório db/migration
--   3. Renomear este arquivo para V1__Schema_Completo.sql
--   4. Subir a aplicação — Flyway aplica só este arquivo
--
-- Tabelas:
--   users — usuários da plataforma (LGPD compliant)
--   envelope_request — envelopes com rastreabilidade completa
--   signer — signatários com status e auditoria
--   document — documentos associados ao envelope
--   requirement — requisitos de qualificação e autenticação
--   envelope_event — auditoria de eventos por envelope
--   envelope_notifier — observadores do envelope
--   outbound_webhook_delivery — histórico de callbacks ao cliente
--   provider_routing_rule — regras de smart routing por usuário
--   audit_log — log de auditoria de acesso à API
-- ================================================================


-- ================================================================
-- USERS
-- LGPD: soft delete (deleted_at), consentimento (consent_at),
--       anonimizadão via deleteMe(), last_login_at para rastreabilidade
-- ================================================================
CREATE TABLE users (
                       id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username      VARCHAR(255) UNIQUE NOT NULL,
                       email         VARCHAR(255),
                       password      VARCHAR(255)        NOT NULL,
                       role          VARCHAR(50)         NOT NULL DEFAULT 'USER',
                       active        BOOLEAN             NOT NULL DEFAULT TRUE,
                       consent_at    TIMESTAMP,
                       last_login_at TIMESTAMP,
                       created_at    TIMESTAMP           NOT NULL DEFAULT NOW(),
                       updated_at    TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
                       deleted_at    TIMESTAMP
);

COMMENT ON COLUMN users.role         IS 'Perfil do usuário: USER | ADMIN | OPERATOR | VIEWER';
COMMENT ON COLUMN users.consent_at   IS 'Data/hora do consentimento LGPD';
COMMENT ON COLUMN users.deleted_at   IS 'Soft delete — preenchido pelo direito ao esquecimento (Art. 18 LGPD)';
COMMENT ON COLUMN users.last_login_at IS 'Último login bem-sucedido';


-- ================================================================
-- ENVELOPE_REQUEST
-- ================================================================
CREATE TABLE envelope_request (
                                  id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  user_id         VARCHAR(255),
                                  name            VARCHAR(255),
                                  provider        VARCHAR(255),
                                  status          VARCHAR(50),
                                  provider_status VARCHAR(255),
                                  callback_url    VARCHAR(500),
                                  external_id     VARCHAR(255) UNIQUE,
                                  created         TIMESTAMP,
                                  updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                                  version         BIGINT       NOT NULL DEFAULT 0
);

COMMENT ON COLUMN envelope_request.status          IS 'Status interno: PROCESSING | ACTIVE | CLOSED | CANCELED | EXPIRED | REFUSED | FAILED | DRAFT | PENDING';
COMMENT ON COLUMN envelope_request.provider_status IS 'Status exato do provedor: running | completed | canceled | draft';
COMMENT ON COLUMN envelope_request.callback_url    IS 'URL para webhook de saída (outbound) — notificação em tempo real ao cliente';


-- ================================================================
-- SIGNER
-- Dados sensíveis (name, email, documentation) criptografados
-- em repouso via EncryptionConverter (AES/GCM/NoPadding)
-- ================================================================
CREATE TABLE signer (
                        id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        external_id      VARCHAR(255) UNIQUE,
                        name             VARCHAR(255),
                        email            VARCHAR(255),
                        documentation    VARCHAR(255),
                        auth_method      VARCHAR(50),
                        status           VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
                        signed_at        TIMESTAMP,
                        ip_address       VARCHAR(100),
                        last_reminded_at TIMESTAMP,
                        envelope_id      BIGINT       NOT NULL,
                        created          TIMESTAMP,
                        CONSTRAINT fk_signer_envelope FOREIGN KEY (envelope_id) REFERENCES envelope_request(id)
);

COMMENT ON COLUMN signer.name          IS 'Nome criptografado em repouso (AES/GCM)';
COMMENT ON COLUMN signer.email         IS 'E-mail criptografado em repouso (AES/GCM)';
COMMENT ON COLUMN signer.documentation IS 'CPF/documento criptografado em repouso (AES/GCM)';
COMMENT ON COLUMN signer.auth_method   IS 'Método de autenticação usado: EMAIL | SMS | WHATSAPP | PIX | HANDWRITTEN | FACIAL_BIOMETRICS | API';
COMMENT ON COLUMN signer.status        IS 'PENDING | SIGNED | REFUSED';
COMMENT ON COLUMN signer.signed_at     IS 'Momento exato da assinatura (preenchido via webhook sign)';
COMMENT ON COLUMN signer.ip_address    IS 'IP do signatário no momento da assinatura';
COMMENT ON COLUMN signer.last_reminded_at IS 'Timestamp do último lembrete enviado — rate limit de 1/hora';


-- ================================================================
-- DOCUMENT
-- ================================================================
CREATE TABLE document (
                          id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          external_id VARCHAR(255) UNIQUE,
                          filename    VARCHAR(255),
                          envelope_id BIGINT       NOT NULL,
                          created     TIMESTAMP,
                          CONSTRAINT fk_document_envelope FOREIGN KEY (envelope_id) REFERENCES envelope_request(id)
);


-- ================================================================
-- REQUIREMENT
-- ================================================================
CREATE TABLE requirement (
                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             external_id VARCHAR(255) UNIQUE,
                             envelope_id BIGINT NOT NULL,
                             document_id BIGINT NOT NULL,
                             signer_id   BIGINT NOT NULL,
                             created     TIMESTAMP,
                             CONSTRAINT fk_requirement_envelope FOREIGN KEY (envelope_id) REFERENCES envelope_request(id),
                             CONSTRAINT fk_requirement_document FOREIGN KEY (document_id) REFERENCES document(id),
                             CONSTRAINT fk_requirement_signer   FOREIGN KEY (signer_id)   REFERENCES signer(id)
);


-- ================================================================
-- ENVELOPE_EVENT
-- Rastreabilidade completa: origem (API/WEBHOOK), evento do provider,
-- signatário responsável, status antes e depois, metadados extras
-- ================================================================
CREATE TABLE envelope_event (
                                id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                envelope_id     BIGINT       NOT NULL,
                                signer_id       BIGINT,
                                previous_status VARCHAR(50),
                                new_status      VARCHAR(50),
                                provider_status VARCHAR(255),
                                provider_event  VARCHAR(100),
                                source          VARCHAR(50),
                                metadata        TEXT,
                                occurred_at     TIMESTAMP,
                                CONSTRAINT fk_event_envelope FOREIGN KEY (envelope_id) REFERENCES envelope_request(id),
                                CONSTRAINT fk_event_signer   FOREIGN KEY (signer_id)   REFERENCES signer(id)
);

COMMENT ON COLUMN envelope_event.source         IS 'Origem da mudança: API | WEBHOOK';
COMMENT ON COLUMN envelope_event.provider_event IS 'Evento exato do provedor: sign | cancel | close | auto_close | deadline | refusal | add_signer | remove_signer';
COMMENT ON COLUMN envelope_event.provider_status IS 'Status exato do provedor no momento do evento: running | completed | canceled | draft';
COMMENT ON COLUMN envelope_event.signer_id      IS 'Signatário que gerou o evento (sign, refusal, add_signer, remove_signer)';
COMMENT ON COLUMN envelope_event.metadata       IS 'Dados extras do provider em formato JSON (ex: chave e2eid do Pix, dados biométricos)';


-- ================================================================
-- ENVELOPE_NOTIFIER
-- Observadores que recebem notificações sem precisar assinar
-- ================================================================
CREATE TABLE envelope_notifier (
                                   id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   envelope_id BIGINT       NOT NULL,
                                   email       VARCHAR(255) NOT NULL,
                                   name        VARCHAR(255),
                                   external_id VARCHAR(255),
                                   created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
                                   CONSTRAINT fk_notifier_envelope FOREIGN KEY (envelope_id) REFERENCES envelope_request(id)
);


-- ================================================================
-- OUTBOUND_WEBHOOK_DELIVERY
-- Rastreia cada tentativa de entrega do callback ao cliente.
-- Suporta retry assíncrono via @Scheduled + next_attempt_at
-- ================================================================
CREATE TABLE outbound_webhook_delivery (
                                           id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           envelope_id     BIGINT       NOT NULL,
                                           url             VARCHAR(500) NOT NULL,
                                           payload         TEXT         NOT NULL,
                                           status          VARCHAR(20)  NOT NULL,
                                           http_status_code INTEGER,
                                           attempts        INT          DEFAULT 0,
                                           last_attempt_at TIMESTAMP,
                                           next_attempt_at TIMESTAMP,
                                           created_at      TIMESTAMP    NOT NULL,
                                           CONSTRAINT fk_webhook_envelope FOREIGN KEY (envelope_id) REFERENCES envelope_request(id)
);

COMMENT ON COLUMN outbound_webhook_delivery.status           IS 'PENDING | SUCCESS | FAILED | PENDING_RETRY';
COMMENT ON COLUMN outbound_webhook_delivery.http_status_code IS 'Código HTTP retornado pela URL do cliente (200, 404, 500...)';
COMMENT ON COLUMN outbound_webhook_delivery.next_attempt_at  IS 'Agendamento do próximo retry (backoff: 60s → 600s)';


-- ================================================================
-- PROVIDER_ROUTING_RULE
-- Regras de smart routing por usuário.
-- O SmartRoutingService avalia em ordem de priority ASC.
-- ================================================================
CREATE TABLE provider_routing_rule (
                                       id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       user_id         VARCHAR(255) NOT NULL,
                                       priority        INT          NOT NULL,
                                       condition_type  VARCHAR(50)  NOT NULL,
                                       condition_value VARCHAR(255),
                                       provider        VARCHAR(50)  NOT NULL,
                                       active          BOOLEAN      DEFAULT TRUE,
                                       created_at      TIMESTAMP    NOT NULL
);

COMMENT ON COLUMN provider_routing_rule.condition_type  IS 'ALWAYS | AUTH_METHOD | COST_THRESHOLD';
COMMENT ON COLUMN provider_routing_rule.condition_value IS 'Valor da condição: ex EMAIL, PIX, 2.50 (custo em reais)';
COMMENT ON COLUMN provider_routing_rule.priority        IS 'Menor número = maior prioridade. Avaliado em ordem ASC.';


-- ================================================================
-- AUDIT_LOG
-- Log de auditoria de acessos e operações críticas.
-- Gravado de forma assíncrona (@Async) — não impacta latência.
-- LGPD: permite rastrear quem acessou quais dados e quando.
-- ================================================================
CREATE TABLE audit_log (
                           id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id       VARCHAR(255),
                           action        VARCHAR(255) NOT NULL,
                           resource_type VARCHAR(100),
                           resource_id   VARCHAR(255),
                           details       TEXT,
                           ip_address    VARCHAR(45),
                           user_agent    TEXT,
                           created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN audit_log.action        IS 'Ex: LOGIN | CREATE_ENVELOPE | CANCEL_ENVELOPE | ACTIVATE_ENVELOPE | VIEW_ENVELOPE | DELETE_ME';
COMMENT ON COLUMN audit_log.resource_type IS 'Ex: ENVELOPE | USER | SIGNER | DOCUMENT';
COMMENT ON COLUMN audit_log.resource_id   IS 'ID do recurso afetado (externalId ou id interno)';


-- ================================================================
-- SEQUENCES — Hibernate 6 usa SEQUENCE por padrão
-- ================================================================
CREATE SEQUENCE IF NOT EXISTS envelope_request_seq        START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS signer_seq                  START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS document_seq                START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS envelope_event_seq          START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS requirement_seq             START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS users_seq                   START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS envelope_notifier_seq       START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS outbound_webhook_delivery_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS provider_routing_rule_seq   START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS audit_log_seq               START WITH 1 INCREMENT BY 50;


-- ================================================================
-- ÍNDICES
-- ================================================================

-- users
CREATE INDEX idx_users_username   ON users(username);
CREATE INDEX idx_users_deleted_at ON users(deleted_at);

-- envelope_request
CREATE INDEX idx_envelope_user_id   ON envelope_request(user_id);
CREATE INDEX idx_envelope_status    ON envelope_request(status);
CREATE INDEX idx_envelope_provider  ON envelope_request(provider);
CREATE INDEX idx_envelope_ext_id    ON envelope_request(external_id);

-- signer
CREATE INDEX idx_signer_envelope    ON signer(envelope_id);
CREATE INDEX idx_signer_external_id ON signer(external_id);
CREATE INDEX idx_signer_status      ON signer(status);

-- document
CREATE INDEX idx_document_envelope  ON document(envelope_id);

-- envelope_event
CREATE INDEX idx_event_envelope_id    ON envelope_event(envelope_id);
CREATE INDEX idx_event_provider_event ON envelope_event(provider_event);
CREATE INDEX idx_event_signer_id      ON envelope_event(signer_id);

-- envelope_notifier
CREATE INDEX idx_notifier_envelope ON envelope_notifier(envelope_id);

-- outbound_webhook_delivery
CREATE INDEX idx_webhook_delivery_envelope ON outbound_webhook_delivery(envelope_id);
CREATE INDEX idx_webhook_delivery_status   ON outbound_webhook_delivery(status, next_attempt_at);

-- provider_routing_rule
CREATE INDEX idx_routing_rule_user_priority ON provider_routing_rule(user_id, priority);

-- audit_log
CREATE INDEX idx_audit_log_user        ON audit_log(user_id);
CREATE INDEX idx_audit_log_resource    ON audit_log(resource_type, resource_id);
CREATE INDEX idx_audit_log_created_at  ON audit_log(created_at);