CREATE TABLE envelope_notifier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    envelope_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    external_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifier_envelope FOREIGN KEY (envelope_id) REFERENCES envelope_request(id)
);
