ALTER TABLE envelope_request ADD COLUMN callback_url VARCHAR(500);

CREATE TABLE outbound_webhook_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    envelope_id BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempts INT DEFAULT 0,
    last_attempt_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_webhook_envelope FOREIGN KEY (envelope_id) REFERENCES envelope_request(id)
);
