CREATE TABLE provider_routing_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    priority INT NOT NULL,
    condition_type VARCHAR(50) NOT NULL, -- 'ALWAYS', 'AUTH_METHOD'
    condition_value VARCHAR(255),
    provider VARCHAR(50) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_routing_rule_user_priority ON provider_routing_rule(user_id, priority);
