-- ================================================================
-- SignFlow — Migration V3
-- Corrige tipos de coluna: SERIAL (INTEGER) → BIGSERIAL (BIGINT)
-- As entidades Java usam Long (@GeneratedValue) que mapeia para
-- BIGINT. O SERIAL criado na V1 é INTEGER — incompatível.
-- ================================================================

-- DOCUMENT
ALTER TABLE DOCUMENT ALTER COLUMN id TYPE BIGINT;
ALTER TABLE DOCUMENT ALTER COLUMN envelope_id TYPE BIGINT;

-- SIGNER
ALTER TABLE SIGNER ALTER COLUMN id TYPE BIGINT;
ALTER TABLE SIGNER ALTER COLUMN envelope_id TYPE BIGINT;

-- ENVELOPE_REQUEST
ALTER TABLE ENVELOPE_REQUEST ALTER COLUMN id TYPE BIGINT;

-- ENVELOPE_EVENT
ALTER TABLE ENVELOPE_EVENT ALTER COLUMN id TYPE BIGINT;
ALTER TABLE ENVELOPE_EVENT ALTER COLUMN envelope_id TYPE BIGINT;

-- REQUIREMENT
ALTER TABLE REQUIREMENT ALTER COLUMN id TYPE BIGINT;
ALTER TABLE REQUIREMENT ALTER COLUMN envelope_id TYPE BIGINT;
ALTER TABLE REQUIREMENT ALTER COLUMN document_id TYPE BIGINT;
ALTER TABLE REQUIREMENT ALTER COLUMN signer_id TYPE BIGINT;

-- USERS
ALTER TABLE users ALTER COLUMN id TYPE BIGINT;